[package]
name = "pafgnostic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
regex = "1"
clap = { version = "4.5.3", features = ["derive"] }
